-- H2 (MySQL 兼容模式) 建表脚本，用于开发与测试
CREATE TABLE IF NOT EXISTS t_user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64),
  phone VARCHAR(20),
  nickname VARCHAR(64),
  avatar VARCHAR(255),
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_family (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  creator_id BIGINT NOT NULL,
  invite_code VARCHAR(16) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_family_member (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  family_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (family_id, user_id)
);

CREATE TABLE IF NOT EXISTS t_ledger (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  type VARCHAR(16) NOT NULL,
  icon VARCHAR(32),
  theme VARCHAR(32),
  owner_id BIGINT NOT NULL,
  family_id BIGINT,
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_ledger_member (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ledger_id, user_id)
);

CREATE TABLE IF NOT EXISTS t_category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  type VARCHAR(16) NOT NULL,
  name VARCHAR(32) NOT NULL,
  icon VARCHAR(32),
  sort INT DEFAULT 0,
  enabled TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_tag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  name VARCHAR(32) NOT NULL,
  color VARCHAR(16),
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_account (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  type VARCHAR(16) NOT NULL,
  name VARCHAR(64) NOT NULL,
  icon VARCHAR(32),
  initial_balance DECIMAL(15,2) DEFAULT 0,
  balance DECIMAL(15,2) DEFAULT 0,
  status TINYINT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_bill (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  type VARCHAR(16) NOT NULL,
  category_id BIGINT,
  member_id BIGINT,
  amount DECIMAL(15,2) NOT NULL,
  bill_date TIMESTAMP NOT NULL,
  remark VARCHAR(255),
  created_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_bill_account (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  bill_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  direction VARCHAR(8) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  pair_id BIGINT,
  INDEX idx_bill (bill_id),
  INDEX idx_account (account_id)
);

CREATE TABLE IF NOT EXISTS t_bill_tag (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  bill_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  UNIQUE (bill_id, tag_id)
);

CREATE TABLE IF NOT EXISTS t_budget (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  period_type VARCHAR(16) NOT NULL,
  start_date DATE,
  end_date DATE,
  remark VARCHAR(64),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_id BIGINT NOT NULL,
  bill_id BIGINT,
  operator_id BIGINT NOT NULL,
  action VARCHAR(16) NOT NULL,
  change_detail VARCHAR(2000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_account_balance_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  old_balance DECIMAL(15,2),
  new_balance DECIMAL(15,2),
  reason VARCHAR(255),
  operator_id BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
